### ISSUE TITLE
Line 20 conflicts with teh delete function of HumHub

### ISSUE THREAD

**Issue by lisandi** [dajanvulaj/humhub-mentionedUsers#1]
```
{
    "url": "/content/content/delete",
    "status": 500,
    "response": {
        "name": "PHP Notice",
        "message": "Trying to get property 'id' of non-object",
        "code": 8,
        "type": "yii\\base\\ErrorException",
        "file": "/[path]/protected/modules/mentionedUsers/Events.php",
        "line": 20,
        "stack-trace": [
            "#0 /[path]/protected/modules/mentionedUsers/Events.php(20): yii\\base\\ErrorHandler->handleError()",
            "#1 [internal function]: humhub\\modules\\mentionedUsers\\Events::onContentDelete()",
            "#2 /[path]/protected/vendor/yiisoft/yii2/base/Event.php(312): call_user_func()",
            "#3 /[path]/protected/vendor/yiisoft/yii2/base/Component.php(637): yii\\base\\Event::trigger()",
            "#4 /[path]/protected/vendor/yiisoft/yii2/db/BaseActiveRecord.php(1027): yii\\base\\Component->trigger()",
            "#5 /[path]/protected/vendor/yiisoft/yii2/db/ActiveRecord.php(750): yii\\db\\BaseActiveRecord->beforeDelete()",
            "#6 /[path]/protected/vendor/yiisoft/yii2/db/ActiveRecord.php(720): yii\\db\\ActiveRecord->deleteInternal()",
            "#7 /[path]/protected/modules/wiki/models/WikiPage.php(189): yii\\db\\ActiveRecord->delete()",
            "#8 /[path]/protected/vendor/yiisoft/yii2/db/ActiveRecord.php(750): humhub\\modules\\wiki\\models\\WikiPage->beforeDelete()",
            "#9 /[path]/protected/vendor/yiisoft/yii2/db/ActiveRecord.php(720): yii\\db\\ActiveRecord->deleteInternal()",
            "#10 /[path]/protected/humhub/modules/content/models/Content.php(298): yii\\db\\ActiveRecord->delete()",
            "#11 /[path]/protected/vendor/yiisoft/yii2/db/ActiveRecord.php(766): humhub\\modules\\content\\models\\Content->afterDelete()",
            "#12 /[path]/protected/vendor/yiisoft/yii2/db/ActiveRecord.php(720): yii\\db\\ActiveRecord->deleteInternal()",
            "#13 /[path]/protected/humhub/modules/content/controllers/ContentController.php(75): yii\\db\\ActiveRecord->delete()",
            "#14 [internal function]: humhub\\modules\\content\\controllers\\ContentController->actionDelete()",
            "#15 /[path]/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array()",
            "#16 /[path]/protected/vendor/yiisoft/yii2/base/Controller.php(181): yii\\base\\InlineAction->runWithParams()",
            "#17 /[path]/protected/vendor/yiisoft/yii2/base/Module.php(534): yii\\base\\Controller->runAction()",
            "#18 /[path]/protected/vendor/yiisoft/yii2/web/Application.php(104): yii\\base\\Module->runAction()",
            "#19 /[path]/protected/vendor/yiisoft/yii2/base/Application.php(392): yii\\web\\Application->handleRequest()",
            "#20 /home/p-school/public_html/index.php(25): yii\\base\\Application->run()",
            "#21 {main}"
        ]
    },
    "textStatus": "error",
    "xhr": {
        "readyState": 4,
        "responseText": "{\"name\":\"PHP Notice\",\"message\":\"Trying to get property 'id' of non-object\",\"code\":8,\"type\":\"yii\\\\base\\\\ErrorException\",\"file\":\"/[path]/protected/modules/mentionedUsers/Events.php\",\"line\":20,\"stack-trace\":[\"#0 /[path]/protected/modules/mentionedUsers/Events.php(20): yii\\\\base\\\\ErrorHandler->handleError()\",\"#1 [internal function]: humhub\\\\modules\\\\mentionedUsers\\\\Events::onContentDelete()\",\"#2 /[path]/protected/vendor/yiisoft/yii2/base/Event.php(312): call_user_func()\",\"#3 /[path]/protected/vendor/yiisoft/yii2/base/Component.php(637): yii\\\\base\\\\Event::trigger()\",\"#4 /[path]/protected/vendor/yiisoft/yii2/db/BaseActiveRecord.php(1027): yii\\\\base\\\\Component->trigger()\",\"#5 /[path]/protected/vendor/yiisoft/yii2/db/ActiveRecord.php(750): yii\\\\db\\\\BaseActiveRecord->beforeDelete()\",\"#6 /[path]/protected/vendor/yiisoft/yii2/db/ActiveRecord.php(720): yii\\\\db\\\\ActiveRecord->deleteInternal()\",\"#7 /[path]/protected/modules/wiki/models/WikiPage.php(189): yii\\\\db\\\\ActiveRecord->delete()\",\"#8 /[path]/protected/vendor/yiisoft/yii2/db/ActiveRecord.php(750): humhub\\\\modules\\\\wiki\\\\models\\\\WikiPage->beforeDelete()\",\"#9 /[path]/protected/vendor/yiisoft/yii2/db/ActiveRecord.php(720): yii\\\\db\\\\ActiveRecord->deleteInternal()\",\"#10 /[path]/protected/humhub/modules/content/models/Content.php(298): yii\\\\db\\\\ActiveRecord->delete()\",\"#11 /[path]/protected/vendor/yiisoft/yii2/db/ActiveRecord.php(766): humhub\\\\modules\\\\content\\\\models\\\\Content->afterDelete()\",\"#12 /[path]/protected/vendor/yiisoft/yii2/db/ActiveRecord.php(720): yii\\\\db\\\\ActiveRecord->deleteInternal()\",\"#13 /[path]/protected/humhub/modules/content/controllers/ContentController.php(75): yii\\\\db\\\\ActiveRecord->delete()\",\"#14 [internal function]: humhub\\\\modules\\\\content\\\\controllers\\\\ContentController->actionDelete()\",\"#15 /[path]/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array()\",\"#16 /[path]/protected/vendor/yiisoft/yii2/base/Controller.php(181): yii\\\\base\\\\InlineAction->runWithParams()\",\"#17 /[path]/protected/vendor/yiisoft/yii2/base/Module.php(534): yii\\\\base\\\\Controller->runAction()\",\"#18 /[path]/protected/vendor/yiisoft/yii2/web/Application.php(104): yii\\\\base\\\\Module->runAction()\",\"#19 /[path]/protected/vendor/yiisoft/yii2/base/Application.php(392): yii\\\\web\\\\Application->handleRequest()\",\"#20 /home/p-school/public_html/index.php(25): yii\\\\base\\\\Application->run()\",\"#21 {main}\"]}",
        "responseJSON": {
            "name": "PHP Notice",
            "message": "Trying to get property 'id' of non-object",
            "code": 8,
            "type": "yii\\base\\ErrorException",
            "file": "/[path]/protected/modules/mentionedUsers/Events.php",
            "line": 20,
            "stack-trace": [
                "#0 /[path]/protected/modules/mentionedUsers/Events.php(20): yii\\base\\ErrorHandler->handleError()",
                "#1 [internal function]: humhub\\modules\\mentionedUsers\\Events::onContentDelete()",
                "#2 /[path]/protected/vendor/yiisoft/yii2/base/Event.php(312): call_user_func()",
                "#3 /[path]/protected/vendor/yiisoft/yii2/base/Component.php(637): yii\\base\\Event::trigger()",
                "#4 /[path]/protected/vendor/yiisoft/yii2/db/BaseActiveRecord.php(1027): yii\\base\\Component->trigger()",
                "#5 /[path]/protected/vendor/yiisoft/yii2/db/ActiveRecord.php(750): yii\\db\\BaseActiveRecord->beforeDelete()",
                "#6 /[path]/protected/vendor/yiisoft/yii2/db/ActiveRecord.php(720): yii\\db\\ActiveRecord->deleteInternal()",
                "#7 /[path]/protected/modules/wiki/models/WikiPage.php(189): yii\\db\\ActiveRecord->delete()",
                "#8 /[path]/protected/vendor/yiisoft/yii2/db/ActiveRecord.php(750): humhub\\modules\\wiki\\models\\WikiPage->beforeDelete()",
                "#9 /[path]/protected/vendor/yiisoft/yii2/db/ActiveRecord.php(720): yii\\db\\ActiveRecord->deleteInternal()",
                "#10 /[path]/protected/humhub/modules/content/models/Content.php(298): yii\\db\\ActiveRecord->delete()",
                "#11 /[path]/protected/vendor/yiisoft/yii2/db/ActiveRecord.php(766): humhub\\modules\\content\\models\\Content->afterDelete()",
                "#12 /[path]/protected/vendor/yiisoft/yii2/db/ActiveRecord.php(720): yii\\db\\ActiveRecord->deleteInternal()",
                "#13 /[path]/protected/humhub/modules/content/controllers/ContentController.php(75): yii\\db\\ActiveRecord->delete()",
                "#14 [internal function]: humhub\\modules\\content\\controllers\\ContentController->actionDelete()",
                "#15 /[path]/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array()",
                "#16 /[path]/protected/vendor/yiisoft/yii2/base/Controller.php(181): yii\\base\\InlineAction->runWithParams()",
                "#17 /[path]/protected/vendor/yiisoft/yii2/base/Module.php(534): yii\\base\\Controller->runAction()",
                "#18 /[path]/protected/vendor/yiisoft/yii2/web/Application.php(104): yii\\base\\Module->runAction()",
                "#19 /[path]/protected/vendor/yiisoft/yii2/base/Application.php(392): yii\\web\\Application->handleRequest()",
                "#20 /home/p-school/public_html/index.php(25): yii\\base\\Application->run()",
                "#21 {main}"
            ]
        },
        "status": 500,
        "statusText": "error"
    },
    "dataType": "json",
    "name": "PHP Notice",
    "message": "Trying to get property 'id' of non-object",
    "code": 8,
    "type": "yii\\base\\ErrorException",
    "file": "/[path]/protected/modules/mentionedUsers/Events.php",
    "line": 20,
    "stack-trace": [
        "#0 /[path]/protected/modules/mentionedUsers/Events.php(20): yii\\base\\ErrorHandler->handleError()",
        "#1 [internal function]: humhub\\modules\\mentionedUsers\\Events::onContentDelete()",
        "#2 /[path]/protected/vendor/yiisoft/yii2/base/Event.php(312): call_user_func()",
        "#3 /[path]/protected/vendor/yiisoft/yii2/base/Component.php(637): yii\\base\\Event::trigger()",
        "#4 /[path]/protected/vendor/yiisoft/yii2/db/BaseActiveRecord.php(1027): yii\\base\\Component->trigger()",
        "#5 /[path]/protected/vendor/yiisoft/yii2/db/ActiveRecord.php(750): yii\\db\\BaseActiveRecord->beforeDelete()",
        "#6 /[path]/protected/vendor/yiisoft/yii2/db/ActiveRecord.php(720): yii\\db\\ActiveRecord->deleteInternal()",
        "#7 /[path]/protected/modules/wiki/models/WikiPage.php(189): yii\\db\\ActiveRecord->delete()",
        "#8 /[path]/protected/vendor/yiisoft/yii2/db/ActiveRecord.php(750): humhub\\modules\\wiki\\models\\WikiPage->beforeDelete()",
        "#9 /[path]/protected/vendor/yiisoft/yii2/db/ActiveRecord.php(720): yii\\db\\ActiveRecord->deleteInternal()",
        "#10 /[path]/protected/humhub/modules/content/models/Content.php(298): yii\\db\\ActiveRecord->delete()",
        "#11 /[path]/protected/vendor/yiisoft/yii2/db/ActiveRecord.php(766): humhub\\modules\\content\\models\\Content->afterDelete()",
        "#12 /[path]/protected/vendor/yiisoft/yii2/db/ActiveRecord.php(720): yii\\db\\ActiveRecord->deleteInternal()",
        "#13 /[path]/protected/humhub/modules/content/controllers/ContentController.php(75): yii\\db\\ActiveRecord->delete()",
        "#14 [internal function]: humhub\\modules\\content\\controllers\\ContentController->actionDelete()",
        "#15 /[path]/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array()",
        "#16 /[path]/protected/vendor/yiisoft/yii2/base/Controller.php(181): yii\\base\\InlineAction->runWithParams()",
        "#17 /[path]/protected/vendor/yiisoft/yii2/base/Module.php(534): yii\\base\\Controller->runAction()",
        "#18 /[path]/protected/vendor/yiisoft/yii2/web/Application.php(104): yii\\base\\Module->runAction()",
        "#19 /[path]/protected/vendor/yiisoft/yii2/base/Application.php(392): yii\\web\\Application->handleRequest()",
        "#20 /home/p-school/public_html/index.php(25): yii\\base\\Application->run()",
        "#21 {main}"
    ],
    "error": {},
    "errorThrown": "",
    "validationError": false
}
    "dataType": "json",
    "name": "PHP Notice",
    "message": "Trying to get property 'id' of non-object",
    "code": 8,
    "type": "yii\\base\\ErrorException",
    "file": "/home/p-school/public_html/h/protected/modules/mentionedUsers/Events.php",
    "line": 20,
    "stack-trace": [
        "#0 /home/p-school/public_html/h/protected/modules/mentionedUsers/Events.php(20): yii\\base\\ErrorHandler->handleError()",
        "#1 [internal function]: humhub\\modules\\mentionedUsers\\Events::onContentDelete()",
        "#2 /home/p-school/public_html/h/protected/vendor/yiisoft/yii2/base/Event.php(312): call_user_func()",
        "#3 /home/p-school/public_html/h/protected/vendor/yiisoft/yii2/base/Component.php(637): yii\\base\\Event::trigger()",
        "#4 /home/p-school/public_html/h/protected/vendor/yiisoft/yii2/db/BaseActiveRecord.php(1027): yii\\base\\Component->trigger()",
        "#5 /home/p-school/public_html/h/protected/vendor/yiisoft/yii2/db/ActiveRecord.php(750): yii\\db\\BaseActiveRecord->beforeDelete()",
        "#6 /home/p-school/public_html/h/protected/vendor/yiisoft/yii2/db/ActiveRecord.php(720): yii\\db\\ActiveRecord->deleteInternal()",
        "#7 /home/p-school/public_html/h/protected/modules/wiki/models/WikiPage.php(189): yii\\db\\ActiveRecord->delete()",
        "#8 /home/p-school/public_html/h/protected/vendor/yiisoft/yii2/db/ActiveRecord.php(750): humhub\\modules\\wiki\\models\\WikiPage->beforeDelete()",
        "#9 /home/p-school/public_html/h/protected/vendor/yiisoft/yii2/db/ActiveRecord.php(720): yii\\db\\ActiveRecord->deleteInternal()",
        "#10 /home/p-school/public_html/h/protected/humhub/modules/content/models/Content.php(298): yii\\db\\ActiveRecord->delete()",
        "#11 /home/p-school/public_html/h/protected/vendor/yiisoft/yii2/db/ActiveRecord.php(766): humhub\\modules\\content\\models\\Content->afterDelete()",
        "#12 /home/p-school/public_html/h/protected/vendor/yiisoft/yii2/db/ActiveRecord.php(720): yii\\db\\ActiveRecord->deleteInternal()",
        "#13 /home/p-school/public_html/h/protected/humhub/modules/content/controllers/ContentController.php(75): yii\\db\\ActiveRecord->delete()",
        "#14 [internal function]: humhub\\modules\\content\\controllers\\ContentController->actionDelete()",
        "#15 /home/p-school/public_html/h/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array()",
        "#16 /home/p-school/public_html/h/protected/vendor/yiisoft/yii2/base/Controller.php(181): yii\\base\\InlineAction->runWithParams()",
        "#17 /home/p-school/public_html/h/protected/vendor/yiisoft/yii2/base/Module.php(534): yii\\base\\Controller->runAction()",
        "#18 /home/p-school/public_html/h/protected/vendor/yiisoft/yii2/web/Application.php(104): yii\\base\\Module->runAction()",
        "#19 /home/p-school/public_html/h/protected/vendor/yiisoft/yii2/base/Application.php(392): yii\\web\\Application->handleRequest()",
        "#20 /home/p-school/public_html/index.php(25): yii\\base\\Application->run()",
        "#21 {main}"
    ],
    "error": {},
    "errorThrown": "",
    "validationError": false
}
```

We deactivated the module and content can again be deleted. Please update and modify the plugin so it will work again in Version 1.9.2 Thanks!

**Comment by luke-** [comment]
See also here: https://github.com/humhub/cfiles/issues/160
